from enum import Enum


class Observations(Enum):
    QUANTITY_IS_ZERO_BY_USER_ACTION = "[USER ACTION][ERROR]: NEWLY ADDED PRODUCTS CANNOT HAVE QUANTITIES EQUAL TO ZERO"
    QUANTITY_IS_ZERO_BY_SYSTEM_PROCESS = "[SYSTEM PROCESS][ERROR]: QUANTITY CANNOT BE ZERO"
    FIRST_DEFINED_STATUS_BY_USER_ACTION = "[USER ACTION]: SETTING FIRST DEFINED STATUS"