from enum import Enum


class ObservationsEnum(Enum):
    QUANTITY_IS_ZERO_BY_USER_ACTION = "[USER ACTION][ERROR]: NEWLY ADDED PRODUCTS CANNOT HAVE QUANTITIES EQUAL TO ZERO"
    QUANTITY_IS_ZERO_BY_SYSTEM_PROCESS = "[SYSTEM PROCESS][ERROR]: QUANTITY CANNOT BE ZERO"
    FIRST_DEFINED_STATUS_BY_USER_ACTION = "[USER ACTION]: SETTING FIRST DEFINED STATUS"
    NO_EXPIRATION_DATE_BY_USER_ACTION = "[USER ACTION]: THERE IS NOT EXPIRATION DATE"
    NO_STATUS_BY_SYSTEM_PROCESS = "[SYSTEM PROCESS][ERROR]: IT'S NOT POSSIBLE TO HAVE AN EXPIRATION DATE WITHOUT STATUS SET"
    NO_EXPIRATION_DATE_BY_SYSTEM_PROCESS = "[SYSTEM PROCESS][ERROR]: IT'S NOT POSSIBLE TO HAVE A STATUS WITH NO EXPIRATION DATE"